### ISSUE TITLE
Add valid input types

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#137]
Please add valid input types to the David UI.  For example, the login screens email field should be type email so it works better on mobile devices.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by cwoolfRuxit** [comment]
Could you please provide some more specific examples? The login screen email field is already of type email.

**Comment by dyladan** [comment]
Is the David UI how we talk to Kennedy now?

**Comment by cwoolfRuxit** [comment]
ba dum tss

**Comment by beeme1mr** [comment]
@cwoolfRuxit nevermind, it looks fine.  Closing the issue.
