### ISSUE TITLE
Slack typing event should reset inactivity timeout

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#139]
controller.on('user_typing', (bot,message) => {
	if (message.user === this.user.id && !this.shouldEndSession) {
		this.lastInteractionTime = moment();
		this.resetInterval = true;
	} else {
		this.resetInterval = false;
	}  	
});

**Comment by beeme1mr** [comment]
https://github.com/Dynatrace/davis-server/blob/web-ui-redesign/app/integrations/slack/index.js

**Comment by dyladan** [comment]
10375b8
