### ISSUE TITLE
upload the filter icon for slack

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#147]

**Comment by beeme1mr** [comment]
We can add another additional colors and sizes as needed.
https://s3.amazonaws.com/dynatrace-davis/assets/images/filter_red_15_15.png
https://s3.amazonaws.com/dynatrace-davis/assets/images/filter_grey_15_15.png
https://s3.amazonaws.com/dynatrace-davis/assets/images/filter_blue_15_15.png

**Comment by dyladan** [comment]
This red is actually green

**Comment by beeme1mr** [comment]
Updated the name to say green instead of red.
