### ISSUE TITLE
Davis Chat Icon is hidden on FF

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#150]
![image](https://cloud.githubusercontent.com/assets/682996/21866061/950b4ba6-d816-11e6-9c91-1cd252a1bca0.png)

**Comment by cwoolfRuxit** [comment]
Won't fix, FF update coming later this month should address this issue.
http://stackoverflow.com/questions/39330512/svg-doesnt-display-on-firefox-but-in-chrome-and-edge-works-fine
