### ISSUE TITLE
Should SYNTHETIC applications be filtered when loading applications on startup?

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#16]
Currently synthetic applications are filtered. filtering was added without much thought when the feature was first implemented, but should it be there?

Reasons to filter:

1. Extra entries in the database that might not get used
2. Synthetic applications are unlikely to be of great interest to people using Davis

Reasons not to filter

1. Could possibly find some use for them in the future.
2. On a `problem` intent, does Davis ever output problems on a synthetic application? If so, we should probably not filter them so that we can give them nice audible names and whatnot.

**Comment by beeme1mr** [comment]
@dyladan I think synthetic applications should be included.  Please confirm and close.

**Comment by dyladan** [comment]
f958e33b7867bc568a31f0892337f2747248b972
