### ISSUE TITLE
Common acronyms should be in all uppercase

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#162]
In v1, we used to have a Nunjucks filter for making all common acronyms uppercase. Can we please restore this functionality at some point?
![capitalization](https://cloud.githubusercontent.com/assets/19412811/22032751/c4660368-dcb3-11e6-9bac-a4a86affa9b5.png)

**Comment by dyladan** [comment]
Fixed in 13fe159
