### ISSUE TITLE
Update the menu when the user is in the settings page

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#164]
It might not be obvious to users that they're able to click the breadcrumbs to navigate back to the davis web UI.  We should update the dropdown menu on the right to include an "interact with davis" section instead of "account settings".

**Comment by cwoolfRuxit** [comment]
They can also click the dynatrace logo to get back to davis. But I see your point. I can toggle that link in the user menu since it's useless when inside Account settings.
