### ISSUE TITLE
web registration

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#166]
maybe we should add account registration with some sort of 'trusted domains' model like what slack does. e.g. all `dynatrace.com` email addresses would be allowed to register non-admin accounts

**Comment by beeme1mr** [comment]
@dyladan this would only make sense once we have email support.  Otherwise, there's no way to validation.

**Comment by beeme1mr** [comment]
Closing this issue because it doesn't make sense at this time.
