### ISSUE TITLE
scalability_many intent not found

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#168]
![scalability_many_intent_bug](https://cloud.githubusercontent.com/assets/19412811/22083486/4d0154e8-dd9a-11e6-8e8d-71c3023b734f.png)

Note:  There is a fix for displaying text only responses checked into filters-config-web-ui-feature branch, so that the message is displayed like in the screenshot. The fix isn't in dev yet, so a type error will show in dev when trying to display this response.

**Comment by beeme1mr** [comment]
This is actually due to the way buttons work now.  Assign to Daniel so he can fix it.

**Comment by dyladan** [comment]
41a805f
