### ISSUE TITLE
Check if bot is listening after a RTM Close event

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#173]
Slacks RTM connection is lost when using a debugger.  This causes the rtm_close event to be fired, which in turn starts a new bot.  We should check if the bot is currently running before started a new one.

**Comment by beeme1mr** [comment]
These should be handled at the same time.
https://github.com/Dynatrace/davis-server/issues/213

**Comment by dyladan** [comment]
can't reproduce as of e4f653e12dabdb39134193887a13a9b450d5547d
