### ISSUE TITLE
Firefox autoselection of chat box does not fill first key

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#174]
# This is a Bug Report

## Description

On Firefox, when the chat box is not selected in the Davis Web UI and a key is pressed, the chat box is selected but the pressed key is not written to the box. This is working in other web browsers.

### For bug reports:

* Description of the issue
* Steps to reproduce
  1. Log in to web UI in firefox
  2. Deselect the chat box
  3. Type Hey davis
* Desired behavior
  - "Hey davis" is typed in the box
* Actual behavior
  - "ey davis" is typed in the box

**Comment by cwoolfRuxit** [comment]
Mike mentioned this issue last week, it should already be fixed in my filters branch.

**Comment by cwoolfRuxit** [comment]
76ae26e73d4186d276f15929d0aabed37d5aed17
