### ISSUE TITLE
Rewrite slack integration to remove the botkit conversation

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#178]
# This is a request for comments

## Description

Rewriting the slack integration would be a lot of work but I believe it could be worth it in order to allow more control over things like buttons both in and out of conversations. With the current scopes model, botkit conversations are already made redundant by the conversations model in the db. Further, it would allow us to have more control over things like allowing a conversation to move between private messages and a public channel, or ignoring all users in a channel until a conversation is concluded with the current user. It would also make the weird hacks that we use to handle buttons outside of the conversation model separately unnecessary because they would simply use the scopes by default. It doesn't make sense to cut out botkit completely because it handles things like OAuth, reconnections, and RTM very nicely for us. Ideally, it would require little to no changes in the rest of Davis, with a special emphasis placed on keeping backwards compatibility with the current plugin architecture so that current plugins are not broken.

## Drawbacks

* This will be a significant amount of work. No getting around that.
* The current system is working, albeit a little difficult to modify or extend at the moment.

## Benefits

* A rewrite of slack with promises will make it easier to debug, modify, extend, and maintain in the future
* More control over the behavior of slack integration, especially with regards to conversations
  * We could make it so Davis does not respond to other users if it is in a conversation with a user in a channel already.
  * We could allow conversations to travel between public and private messages
  * We could enable conversations with multiple people in a slack channel (this is probably a lot of work with less benefit, but illustrates a case that would not be possible with the current system)

Anybody have any thoughts on this? Comments or concerns?

**Comment by cwoolfRuxit** [comment]
I understand the benefits, but there's a lot of other items I think we should focus on before this. My next priorities include adding back Watson support in the web UI, help pages, push notifications in extension and web UI, etc. I don't think we ever actually use RTM, since it doesn't support anything other than text (no attachments) from my understanding.

**Comment by dyladan** [comment]
* | e742f2e - Keep exchange filter information accross paging (2 hours ago) <Daniel Dyla>
* | b455759 - fix filtered authoring in slack (2 hours ago) <Daniel Dyla>
* | 8079e19 - fix author_name property name (2 hours ago) <Daniel Dyla>
* | 0cbdcbc - move slack out of folder because it is only one file (2 hours ago) <Daniel Dyla>
* | 2d7ca4c - button ownership and footers implemented (3 days ago) <Daniel Dyla>
* | 382ba0e - Button support added (4 days ago) <Daniel Dyla>
* | 953fa68 - Basic slack conversation question/answer working (5 days ago) <Daniel Dyla>
