### ISSUE TITLE
Filtered responses that are text only don't include author property

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#187]
# This is a Bug Report
## Description
* Steps to reproduce

1. Add new filter with `web:{your-account-email}` scope, as well as `Closed, Application, and Error` selected
2. Ask davis (web UI) `what happened at 1pm?` or another specific time that results in a text only response
3. Notice that the author property isn't used since attachments aren't used

* Desired behavior
Always use cards for responses that can be filtered so that the author property can be set to filtered

Note: It also appears that audible responses don't include anything about a filter being used, which could be problematic if the user doesn't remember or know a filter has been applied. I realize Alexa isn't supported yet for filtering, so this is more of a ToDo.

![text-only-response-filter-author-not-included](https://cloud.githubusercontent.com/assets/19412811/22337603/6173e0fc-e3b3-11e6-83ee-70eb718c6073.png)

**Comment by cwoolfRuxit** [comment]
Also, shouldn't we not allow users to ask about the future, like above?

**Comment by dyladan** [comment]
@cwoolfRuxit Can you give me an example of a future query?

**Comment by dyladan** [comment]
<img width="823" alt="screen shot 2017-01-31 at 1 22 26 pm" src="https://cloud.githubusercontent.com/assets/1612643/22478549/61c285e6-e7b8-11e6-9030-959d415025b0.png">
