### ISSUE TITLE
Extend the problem details to include the impacted application.

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#190]
# This is a Feature Proposal

## Description

A user should be able to quickly identify what application was impacted when looking at the details of a application level event.

This is what we show:

![image](https://cloud.githubusercontent.com/assets/682996/22373348/61abddc4-e46f-11e6-8696-308e8198d3de.png)

This is what the tenant shows:
https://cdojfgmpzd.live.dynatrace.com/#problems;filter=watched/problemdetails;pid=-4251007454308999334
![image](https://cloud.githubusercontent.com/assets/682996/22373392/a74dec32-e46f-11e6-82a6-3d01fad97d81.png)

**Comment by dyladan** [comment]
000b1f04e8fe8f4d69d897435ee868d1e0fa0f0d
