### ISSUE TITLE
Support right-click "open link in new tab" on cards

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#193]
It looks like adding an href should do the trick.

**Comment by dyladan** [comment]
you will also need to override default behavior in the onclick handler by returning false in your handler

**Comment by beeme1mr** [comment]
the onclick handler already works how you would expect, right?  Would this allow you to ctrl + click?

**Comment by dyladan** [comment]
if you simply add a `href` attribute, the default handler and cory's handler will both fire, which means a regular click will open in a new tab and in the current tab and a ctrl+click will open 2 new tabs
