### ISSUE TITLE
Paging context/paging issue

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#195]
Calling next on the last page confuses davis.

![image](https://cloud.githubusercontent.com/assets/682996/22386814/c47bd882-e4a6-11e6-8000-e1b13a3cbcca.png)
![image](https://cloud.githubusercontent.com/assets/682996/22386818/cd228648-e4a6-11e6-8796-1122d904e988.png)

**Comment by beeme1mr** [comment]
I can't seem to recreate it now.

**Comment by dyladan** [comment]
74cbdbf5e7765dd46dac1b12e9f2faa267cad205
