### ISSUE TITLE
Pager assumes show and text are being passed in

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#196]
# This is an observation

## Description

Right now the pager assumes that the items list is a list of objects of the following form:

```
{
  show: Message object
  text: String
  id: Unique identifier for this item
  say: this field is ignored for now
}
```

In the future we need to extend the pager to accept any combination of one or more of these datatypes (except id, i believe that should probably be required)

**Comment by beeme1mr** [comment]
This is resolved in the multi tenant branch
