### ISSUE TITLE
recent issues not working

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#197]
![image](https://cloud.githubusercontent.com/assets/682996/22390201/b2a816fa-e4b7-11e6-8744-703f65e1c321.png)

**Comment by dyladan** [comment]
2a608d5

<img width="784" alt="screen shot 2017-01-31 at 2 55 51 pm" src="https://cloud.githubusercontent.com/assets/1612643/22482087/808473d8-e7c5-11e6-8ef2-d938097eddab.png">
