### ISSUE TITLE
"any issues" doesn't result in problem intent

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#205]
# This is a Bug Report

## Description
The phrases for the problem plugin include "any issues", but using the phrase doesn't result in the problem intent. Very minor issue.

<img width="791" alt="screen shot 2017-02-01 at 3 10 44 pm" src="https://cloud.githubusercontent.com/assets/19412811/22527597/cf4ecec2-e89d-11e6-9c8f-efffaa124ee8.png">

**Comment by dyladan** [comment]
df3177e1f5106430c63d91fd3edc1166f4b48a14
