### ISSUE TITLE
Add a problem state parser to NLP

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#21]
We to give users the option to ask for the status of open or closed issues. @cwoolfRuxit had worked on this functionality in Davis V1 but now we need to move it to the NLP class.

```JavaScript
const STATUS = {
  OPEN: 1,
  CLOSED: 2,
}

const STATUS_TRANSLATIONS = {
  resolved: STATUS.CLOSED,
  unresolved: STATUS.OPEN,
  solved: STATUS.CLOSED,
  unsolved: STATUS.OPEN,
  inactive: STATUS.CLOSED,
  active: STATUS.OPEN,
  closed: STATUS.CLOSED,
  open: STATUS.OPEN,
  any: null,
};
```

@cwoolfRuxit, mike told me to get with you to figure out the requirements for this piece.

**Comment by beeme1mr** [comment]
@dyladan We might want to create a new ticket based on your last comment.  The original ticket no longer makes sense though.

**Comment by dyladan** [comment]
I agree. Closing in favor of #216
