### ISSUE TITLE
reap old exchanges from the database

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#214]
# This is a Feature Proposal

## Description

My local development database is over 80MB, most of which is old exchanges. I have a little over 1000 exchanges, and the average one is over 70k bytes. The reason for this is twofold:

1. We store every exchange indefinitely.
2. We constantly merge and re-store context, causing each exchange to be larger than the exchange before it on average.

Possible solutions would be:

1. Periodically remove all exchanges more than x days old.
2. Periodically remove the context objects from any exchange more than x days old.
3. Do not persist the context object to the database. Instead, store only the current context object in memory.
4. Store the context object on the conversations model rather than the exchanges model, and simply update it in place rather than storing a new object on every exchange.
5. ???

**Comment by beeme1mr** [comment]
@dyladan Did your change yesterday resolve this issue?

**Comment by dyladan** [comment]
yes
