### ISSUE TITLE
use Double Metaphone + Levenshtein to match application names and arbitrary datatypes

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/davis-server#216]
# This is a Feature Proposal

## Description

Double Metaphone is an algorithm for transforming words into a representation such that it will be similar to the Double Metaphone representation of similar sounding words, even if the spelling is very different. This makes sure that words like 'know' and 'no' that sound the same but are spelled differently are represented the same way or at least closely. Then a Levenshtein distance calculation calculates the edit distance from the search term to the text being matched against. For instance: Easy Travel would be represented by Double Metaphone as ASTRFL. This allows it to be matched against imperfect pronunciations such as e three travel (A0RTRFL distance 2).  I think this may really improve our application matching accuracy and should even be considered as a step in the NLP module before classification.

## Example Matches

For each match I will show the Double Metaphone representation and the Levenshtein distance

### Easy Travel (ASTRFL)

- e z travel - ASTRFL 0
- easy trouble - ASTRPL 1

### Madison Island (MTSNLNT)

- mad is an island - MTSNLNT 0
- mad dis and i land - MTTSNTLNT 2

## Description of Use

First, an array of the DM representation would be computed and stored for every name and alias of every application. When a request comes in, it would be broken into n-grams like `['the', 'lazy', 'dog', 'walks', 'the lazy', 'lazy dog', 'dog walks', 'the lazy dog', 'lazy dog walks', 'the lazy dog walks']`. The DM representation would then be calculated for every n-gram: `[ '0', 'LS', 'TK', 'ALKS', '0LS', 'LSTK', 'TKLKS', '0LSTK', 'LSTKLKS', '0LSTKLKS' ]`. After this, each n-gram would be given a Levenshtein distance score agains the DM representation of each application. For instance, for the application 'Crazy Dog' (KRSTK), the levenshtein distances would be `[ 5, 4, 3, 5, 4, 2, 5, 2, 5, 5 ]`. This means that 'LSTK' (lazy dog) and '0LSTK' (the lazy dog) are the two closest representations. After defining some minimum threshold through testing, This could be used to match even some of the crazy outputs we get from alexa (ALKS).

### Overview of Steps

1. Input: `The lazy dog walks.`
2. Tokenization: `['the', 'lazy', 'dog', walks']`
3. N-Grams: `['the', 'lazy', 'dog', 'walks', 'the lazy', 'lazy dog', 'dog walks', 'the lazy dog', 'lazy dog walks', 'the lazy dog walks']`
4. Double Metaphone: `[ '0', 'LS', 'TK', 'ALKS', '0LS', 'LSTK', 'TKLKS', '0LSTK', 'LSTKLKS', '0LSTKLKS' ]`
5. For each application
    1. Input: `Crazy Dog`
    2. Double Metaphone: `KRSTK`
    3. Levenshtein: `[ 5, 4, 3, 5, 4, 2, 5, 2, 5, 5 ]`
    4. Minimum: `2`
    5. If under threshold `x`, match is confirmed

## Timing

- Calculating the DM for every word in my laptop's dictionary takes 547 ms.
    - `dict.toString().split('\n').map(dm)`
- Calculating the string distance between KRSTK and the DM for every word takes 1.3 seconds (including the conversion of the word to DM).
    - `dict.toString().split('\n').map(dm).map(a => new l(a[0], 'KRSTK').distance)`

**Comment by beeme1mr** [comment]
Added in multi-tenant branch
