### ISSUE TITLE
Test Custom Alerts

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#223]
# This is a Task

## Description

Custom alerts in Dynatrace tend to be critically important because a user has gone out of their way to configure one.  That mean, we need to ensure that davis is able to parse custom problems in order to highlight the important aspects.

### For feature proposals:

- [ ] Parse a custom alert
- [ ] Test push notifications
- [ ] See if the current filtering system handles most of the potential use cases
- [ ] Test the problem overview and details of a custom alert via Slack and Alexa

**Comment by danielkhan** [comment]
Please provide end-to-end use case.
