### ISSUE TITLE
Clear old Dynatrace info when the tenant changes

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#232]
# This is an enhancement

## Description

Davis caches application and service information in Mongo but this information would become stale if a user changes what tenant they're pointing to.  We should detect if the tenant changes and purge the appropriate information from the db.

### For feature proposals:

* Detect a tenant URL change
* Purge tenant specific data from Mongo

**Comment by dyladan** [comment]
2e06ca560087a745747274cea9d14b562d88e450
