### ISSUE TITLE
Image support in web UI cards

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#238]
# This is a Feature Proposal

## Description
Add support for displaying images in web UI card based on Slack card JSON

**Comment by beeme1mr** [comment]
Please add support for the "image_url" attachment property.


* [Docs](https://api.slack.com/docs/message-attachments)
* [Example](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Network%20traffic%20(kb%2Fs)%3A%20How%20does%20this%20look%3F%20%40slack-ops%20-%20Sent%20by%20Julie%20Dodd%20-%20https%3A%2F%2Fdatadog.com%2Fpath%2Fto%2Fevent%22%2C%22title%22%3A%22Network%20traffic%20(kb%2Fs)%22%2C%22title_link%22%3A%22https%3A%2F%2Fdatadog.com%2Fpath%2Fto%2Fevent%22%2C%22text%22%3A%22How%20does%20this%20look%3F%20%40slack-ops%20-%20Sent%20by%20Julie%20Dodd%22%2C%22image_url%22%3A%22http%3A%2F%2Fwww.excel-easy.com%2Fdata-analysis%2Fimages%2Fcharts%2Fcolumn-chart.png%22%2C%22color%22%3A%22%23764FA5%22%7D%5D%7D)

NOTE: Large images will be resized to a maximum width of 400px or a maximum height of 500px, while still maintaining the original aspect ratio.

**Comment by cwoolfRuxit** [comment]
We actually had support for image_url in the v1 web UI, so I should be able to borrow some styling.

**Comment by cwoolfRuxit** [comment]
Full screen image positioning fixed
6842d15029f38ca9e4e327a3e6c58e4437f9ad24
