### ISSUE TITLE
Fix multi-team support

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#241]
# This is a Bug Report

## Description

Davis seems to be running into a number of issues when in a multi-team environment.  It appears as though the Slack payload changes slightly.

The message object contains "source_team" instead of "team".

### For bug reports:

* Configure Davis with at least two Slack teams
* Attempt to talk to Davis via Slack

**Comment by dyladan** [comment]
after testing this appears to not be a bug anymore? I'm not really happy closing this without knowing more about what caused it but it seems that it is fixed either way. I'm going to close this. @beeme1mr can reopen it if he feels it should be open.
