### ISSUE TITLE
Use Secure Cookies for persisting JWT on page refresh in web UI

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#242]
# This is an Enhancement

## Description
Instead of storing the user's JSON Web Token in sessionStorage, store it in a Secure Cookie for better security (prevent XSS attacks).

**Comment by dyladan** [comment]
After this is done we should probably take a look at adding CSRF tokens to the web UI.

**Comment by beeme1mr** [comment]
This will be resolved once the multi-tenant system is ready.
