### ISSUE TITLE
How to leave the Configuration screen

### ISSUE THREAD

**Issue by dlopes7** [Dynatrace/davis-server#249]
I'm sorry if this is a dumb question,

I'm following the "[Creating Custom Plugins](https://github.com/Dynatrace/davis-server/wiki/Creating%20Custom%20Plugins)" wiki page.  
  
I've started Davis, created an admin user with the web interface, connected it to my Dynatrace Tenant.  
  
But how do I leave the configuration screen? I want to go to the "main" page where I can type questions, am I missing something obvious here?  

Thanks for the great project!

**Comment by dlopes7** [comment]
Nevermind, I copied the package.json on the wiki page and that comes with davis version 0.4.1. Using the latest version of Davis fixed all my issues.

**Comment by beeme1mr** [comment]
@dlopes7 Thanks for reporting this.
