### ISSUE TITLE
Plugin phrases are case sensitive

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#251]
# This is a Bug Report

## Description
The plugin phrases used to train davis for intent recognition are case sensitive. Since the phrases might be used in examples, we should allow mixed case to be used.

![phrases-capitalization-bug](https://cloud.githubusercontent.com/assets/19412811/23723464/4ed3415c-0417-11e7-8673-214d2540e81b.png)

**Comment by dyladan** [comment]
1324104942bb8f0ef1ac111337b634de903009f6
