### ISSUE TITLE
Update content of slack card to be more descriptive of actual problem

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#252]
# This is an Enhancement

## Description
The Problem plugin's visual card response should include the application name in the attachment title, instead of below in a separate field.

From discussion with @danielkhan 
We always have a problem X caused by Y where Y is an entity and not an event. In some cases we are not sure what Y is, then we can provide possible causes. If there are several events connected to Y we don't have to provide them in the textual response. So we end up with a "We have/had user response time degradation on EasyTravel caused by MongoDB" that's always better than 'Closed Application Level problem'

**Comment by dyladan** [comment]
683675effb76c6cd7d1b662addc95fb01b8ef024

**Comment by cwoolfRuxit** [comment]
@dyladan Can we close this?
