### ISSUE TITLE
Slack wont start because of invalid client token

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#255]
# This is a Bug Report

## Description

The botkit mongo dependency is using monk version 2.  This version of monk seems to be incompatible with the latest version of MongoDB.

https://github.com/Automattic/monk/issues/180

This causes the Slack app registration process to fail because of an invalid client token.  The token is thought to be invalid because it fails to save to mongodb.

### For bug reports:

* Grab the latest version of Davis
* Attempt to configure Slack

### Temporary fix:
* Add ```"mongodb": "2.2.21"``` to package.json
* rm -rf node_modules/mongodb/*
* npm install

## Full fix:
* Fork https://github.com/howdyai/botkit-storage-mongo
* Update monk to version 4
* Submit PR
* Update Davis to point to the fork until Howdyai accepts the PR.

**Comment by dyladan** [comment]
6602ad799f057b84b9999ef54878735c9e7bed5a
