### ISSUE TITLE
Voice Navigator Link

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#264]
Please update the link on the voice navigation page to reflect the change in wiki.

old: https://github.com/Dynatrace/davis-server/wiki/Setup%20Chrome%20Extension
new: https://github.com/Dynatrace/davis-server/wiki/Setup-Voice-Navigator

**Comment by cwoolfRuxit** [comment]
224359800ef81989d1b5688a254db729a8d3370b
