### ISSUE TITLE
Not able to create admin account

### ISSUE THREAD

**Issue by thomas-rotte** [Dynatrace/davis-server#274]
# This is a Bug Report

## Description

I am installing the davis server through the heroku paas, but when completing the wizard, i keep on getting "A user with that email address already exists.", while i tried with a number of surely unused emailadresses

### For bug reports:

* Description of the issue
I am installing the davis server through the heroku paas, but when completing the wizard, i keep on getting "A user with that email address already exists.", while i tried with a number of surely unused emailadresses

* Steps to reproduce
clean install => follow the wizard => fill in page 2 with a random emailadress

* Desired behavior
take me to step 3 in the wizard...

* Actual behavior
error message keeps popping up:
"A user with that email address already exists."

**Comment by beeme1mr** [comment]
@thomas-rotte I'm sorry you were having trouble with the wizard.  I was able to reproduce the issue you reported.  I'll try and have a fix ASAP.  Thanks for reporting the issue.

**Comment by beeme1mr** [comment]
I've pushed out a fix.  Please delete your Heroku app and try again.

**Comment by thomas-rotte** [comment]
beeme1mr; i want to thank you for the quick reply, and the fast solution you provided.
Excelent work!!!

Currently, i am using my Alexa to communicate to a Davis handling issues for my Dynatrace systems!
perfect
