### ISSUE TITLE
Error when querying for user activity levels

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/davis-server#276]
I use a Davis Server on heroku connected to a Dynatrace Managed instance.

When querying for user activity levels I get an error: Must set a response

![image](https://user-images.githubusercontent.com/5699104/28156931-f771af5a-67b4-11e7-964d-1c5109235b08.png)

I get this result for all question regarding user activity levels, all other question work fine.
This happens weather there are active user sesssion or not.

**Comment by beeme1mr** [comment]
@pahofmann would you be able to attach the logs?

**Comment by pahofmann** [comment]
Of course, it changed to "An unhandled error has occurred" now, here is the log:
[amasoldavis-logs-1499958436708.txt](https://github.com/Dynatrace/davis-server/files/1145633/amasoldavis-logs-1499958436708.txt)

**Comment by beeme1mr** [comment]
@pahofmann thanks for attaching the logs.  It looks the managed instance you're on doesn't support the prediction API.  This should be a straightforward change and we'll try and have something to release in the next few hours.

**Comment by pahofmann** [comment]
Great to hear, thanks! Just let me know if you need more information or want me to test anything :)

**Comment by dyladan** [comment]
This stems from the fact that the managed tenant hasn't been updated to have the user activity prediction. Pushed a fix that should be released soon. @beeme1mr please close this ticket after release.

**Comment by dyladan** [comment]
No problem we appreciate the feedback

**Comment by beeme1mr** [comment]
@pahofmann Version 0.19.2 has been released to address this issue.  Please perform an update and let us know if that resolves the issue.

We've documented the process for upgrading on Heroku [here](https://github.com/Dynatrace/davis-server/wiki/Update).

**Comment by pahofmann** [comment]
There are some errors/warnings when doing the npm update, here is the log:
[amasoldavis-console-1499962873601.txt](https://github.com/Dynatrace/davis-server/files/1145872/amasoldavis-console-1499962873601.txt)

**Comment by beeme1mr** [comment]
Would you be able to try to rebuild your node modules.  This guide should get you started.

https://coderwall.com/p/jjcpra/clean-heroku-npm-cache

If that still doesn't work, would you mind rebuilding your environment?  I just created a brand new app on Heroku with no issues.  If this isn't an option, we'll do our best to figure out the root cause.

**Comment by pahofmann** [comment]
I tried redeploying it, but ran into an error there aswell:
![image](https://user-images.githubusercontent.com/5699104/28179448-451afd2c-6802-11e7-9fa1-47793ee90a13.png)

**Comment by pahofmann** [comment]
The second redeploy worked, the issue is fixed now.
Thanks for the quick help!
