### ISSUE TITLE
Problems Investigation started even if answer was "no"

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/davis-server#277]
I have found a bug with the intention parsing.

When invoking davis via the alexa skill, if there are any open issue he will ask you if you want to investigate them. Even if you answer "no", the issue investigation is always started.

Tested this with the saas version (https://cloudcontrol.davis.dynatracelabs.com/davis) and my own davis server.

**Comment by beeme1mr** [comment]
I wasn't able to reproduce the issue.  Could you please attach the logs?

**Comment by pahofmann** [comment]
I couldn't reproduce it yet in the managed environment because there where no Problems.
I'll attach a log as soon as I can reproduce it there.

**Comment by pahofmann** [comment]
Here is the log file: [amasoldavis-logs-1500896983134.txt](https://github.com/Dynatrace/davis-server/files/1169716/amasoldavis-logs-1500896983134.txt)

It recives a 'no' from alexa here:
`2017-07-24T11:49:16.058993+00:00 app[web.1]: [2017-07-24T11:49:16.058Z] INFO: Starting a new exchange from alexa: 'no'`
but then still opens the problem dashboard.

**Comment by beeme1mr** [comment]
Thanks, we're investigating.

**Comment by beeme1mr** [comment]
@pahofmann we pushed out a fix.  Also, would you mind sending an email to michael.beemer@dynatrace.com?  We would be interested in having you join an EAP.

**Comment by pahofmann** [comment]
Tested it, the fix is working fine.
