### ISSUE TITLE
Remove Custom Slots from the Alexa integration

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#54]
Amazon is deprecating the string literal slot.  We need to find a way to continue receiving the entire string from Alexa.

**Comment by dyladan** [comment]
@beeme1mr have you tested this? If so I'm happy to add it to the documentation and close this

**Comment by beeme1mr** [comment]
I haven't tested it yet.  I was thinking about trying to add in some actual phrases in the custom slot type.  It should improve accuracy on those commands.  The only downside is that most users won't update this list and it could end up negatively impacting new plugins.

**Comment by dyladan** [comment]
and so here we are back to wishing for programmatic access to the API. I guess this stays open for now then

**Comment by beeme1mr** [comment]
https://github.com/Dynatrace/davis-server/wiki/Setup-Alexa/5f6e3a1e612a97ccb86962330a8371c26fe7b164
