### ISSUE TITLE
Port v1 web UI to Angular 2

### ISSUE THREAD

**Issue by cwoolfRuxit** [Dynatrace/davis-server#56]
- [x] REST calls
- [x] UI binding
- [x] Visual interaction logic
- [ ] Audible interaction logic
- [x] Styling (Responsive Design)

**Comment by beeme1mr** [comment]
@cwoolfRuxit Can this issue be closed?

**Comment by cwoolfRuxit** [comment]
@beeme1mr We still haven't ported voice interaction, I was going to use it for that.

**Comment by cwoolfRuxit** [comment]
New issue created for Watson STT/TTS, closing this one now.
