### ISSUE TITLE
Create release automation workflow

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#76]
- [ ] npm test
- [x] git checkout dev
- [ ] bump version
- [ ] optional - create changelog
- [ ] git commit
- [ ] git push
- [ ] git checkout master
- [ ] git merge dev
- [ ] gulp compile:prod
- [ ] optional - UI tests
- [ ] git push
- [ ] npm pack .
- [ ] optional - create github release
- [ ] npm publish

**Comment by dyladan** [comment]
Only thing is this does not run tests and does not npm publish at the moment but it is close enough that I am closing this.
