### ISSUE TITLE
Create a API that returns the current version.

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#84]

**Comment by dyladan** [comment]
Should this be extended to be a more general metadata endpoint? Other things that you might want for similar reasons:

- node version
- mongo version
- node_env
- uptime (for davis, host, or both)

I'm sure there would be other things as well

**Comment by beeme1mr** [comment]
Makes sense to include additional information.  Perhaps we should also add:

- up to date boolean
- last version available (probably on NPM)

**Comment by dyladan** [comment]
0c26873

**Comment by dyladan** [comment]
Oops just closed the wrong one

**Comment by dyladan** [comment]
@beeme1mr how does `/api/v1/system/meta` sound as an endpoint? I'm torn between `meta` and `info`

**Comment by dyladan** [comment]
also should this be restricted to admin users?

**Comment by beeme1mr** [comment]
@dyladan Yes, admin only and I prefer info.

**Comment by dyladan** [comment]
b23dc92
