### ISSUE TITLE
Add an audit REST API

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#86]
An audit REST API would be useful for many purposes.  Once created, the UI should be updated to include this new data.

Admin:
GET - /api/v1/system/audit - Returns the last X number of interactions
GET - /api/v1/system/audit/user@email.com - Returns the last X number of interactions for a specific user

User:
GET - /api/v1/system/audit/user@email.com - Returns the last X number of interactions the logged in user.

The response should include:

- Time
- User Email
- Source
- Request
- Plugin Run
- Response

**Comment by dyladan** [comment]
2 and 3 appear to be the same endpoint

**Comment by dyladan** [comment]
oh i see the difference. should the first one be across all users?

**Comment by dyladan** [comment]
@beeme1mr when you say 'interaction', what sort of data would you expect this to return? Would it be like the raw request and response? Or a list of exchange objects?
