### ISSUE TITLE
Extend "Show me" functionality

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#87]
We should extend the "show me" functionality to allow users to skip the normal flow and get the link sent. This means we should handle the following use cases:
- Most should plugins should set a URL.
- Add phrases and regex to show me plugin.
- Handle use cases when the plugin isn't connected.
- Perhaps add a confirmation if the URL was set too long ago.

**Comment by dyladan** [comment]
so do we want. "send that to my browser" to work at all times? If there is no url it will just say "I'm not sure what you wanted sent" or something along those lines

**Comment by beeme1mr** [comment]
Exactly.
