### ISSUE TITLE
Add Synthetic location to Davis proactive alert

### ISSUE THREAD

**Issue by david-kennedy** [Dynatrace/davis-server#93]
![image](https://cloud.githubusercontent.com/assets/13055118/21430308/abe9c118-c830-11e6-9202-c3d306659a70.png)

**Comment by dyladan** [comment]
not sure what you mean by "add synthetic location"

**Comment by david-kennedy** [comment]
Synthetic Response time come from pre-recorded scripts that run from locations around the world like Singapore, London, or Frnakfurt. Sometimes these alerts are for 1 location, or many. For example, this one I believe (once clicked on) was related to a slowdown in Singapore, where the rest of the global location performance was ok.

**Comment by dyladan** [comment]
@david-kennedy this is in dev now
